# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Whatsapp
version: "2.4.1"
slug: whatsapp
description: Whatsapp integration for Home Assistant.
url: "https://github.com/gajosu/whatsapp-ha-addon/tree/master/whatsapp"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw

options:
  webserver_port: 3000
schema:
  webserver_port: "int"

ports:
  3000/tcp: 3000

ports_description:
  3000/tcp: The webserver port (Not used for Ingress).
# image: "ghcr.io/gajosu/amd64-whatsapp-ha-addon:2.0.0"
homeassistant_api: true
